version: '3'
services:
    tomato:
        build:
          context: .
          dockerfile: Dockerfile.test
        volumes:
          - postgres-initdb:/db/postgres/
          - mysql-initdb:/db/mysql/
          - /tmp/:/tmp/

    rabbit:
        image: rabbitmq:3.6.1-management
        expose:
            - "5672"

    postgres:
        image: postgres:9.5
        expose:
            - "5432"
        environment:
            POSTGRES_USER: tomato
            POSTGRES_PASSWORD: potato
            POSTGRES_DB: tomato
        volumes:
            - postgres-initdb:/docker-entrypoint-initdb.d/

    mysql:
        image: mysql:5.6.34
        expose:
            - "3306"
        environment:
            - MYSQL_ROOT_PASSWORD=potato
            - MYSQL_DATABASE=tomato
        volumes:
            - mysql-initdb:/docker-entrypoint-initdb.d/

    nsqd:
        image: nsqio/nsq
        expose:
            - "4150"
        entrypoint: ["/nsqd"]

    wiremock:
        image: rodolpheche/wiremock
        ports:
          - "8080"
        expose:
            - "8080"

    redis:
        image: redis:5.0.6-alpine
        ports:
            - "6379"
        expose:
            - "6379"

volumes:
  postgres-initdb: {}
  mysql-initdb: {}
