# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10

    working_directory: /go/src/github.com/alileza/tomato
    steps:
      - checkout

      - run: go get -u github.com/go-playground/overalls
      - run: overalls -project=github.com/alileza/tomato -covermode=atomic -debug -- -race -v
      - run: mv overalls.coverprofile coverage.txt
      - run: bash <(curl -s https://codecov.io/bash)

  test:
    docker:
      - image: docker/compose:1.22.0

    working_directory: /go/src/github.com/alileza/tomato
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: run integration test
          command: docker-compose up --exit-code-from tomato

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
