# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.10

      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: tomato
          POSTGRES_PASSWORD: potato
          POSTGRES_DB: tomato

      - image: mysql:5.6.34
        environment:
            - MYSQL_ROOT_PASSWORD=potato
            - MYSQL_DATABASE=tomato

      - image: rabbitmq:3.6.1-management

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/postgres:9.4

    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/alileza/tomato
    steps:
      - checkout

      - run: curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
      - run: dep ensure
      - run: go get -u github.com/go-playground/overalls
      - run: overalls -project=github.com/alileza/tomato -covermode=atomic -debug -- -race -v
      - run: mv overalls.coverprofile coverage.txt
      - run: bash <(curl -s https://codecov.io/bash)

      - run:
          name: building tomato binaries
          command: make build
      - run:
          name: generating handler
          command: ./bin/tomatool generate handler -d ./dictionary.yml -o handler/handler.go
      - run:
          name: installing database migration tools
          command: go get -u github.com/pressly/goose/cmd/goose
      - run:
          name: waiting for PostgreSQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5432 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for PostgreSQL && exit 1
      - run:
          name: waiting for MySQL to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 3306 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for MySQL && exit 1
      - run:
          name: run database migration
          command: |
            goose -dir examples/db/postgres/ postgres "user=tomato password=potato dbname=tomato sslmode=disable" up
            goose -dir examples/db/mysql/ mysql "root:potato@/tomato?parseTime=true" up

      - run:
          name: waiting for RabbitMQ to be ready
          command: |
            for i in `seq 1 10`;
            do
              nc -z localhost 5672 && echo Success && exit 0
              echo -n .
              sleep 1
            done
            echo Failed waiting for RabbitMQ && exit 1

      - run:
          name: run integration test
          command: |
            ./bin/tomato -c examples/config.yml -f examples/features/database.feature
            ./bin/tomato -c examples/config.yml -f examples/features/queue.feature
