version: 2
jobs:
  dictionary-check:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/tomatool/tomato
    steps:
      - checkout

      - run:
          name: check consistency generated documentation and handler
          command: make check

  unit-test:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/tomatool/tomato
    steps:
      - checkout

      - run: go get -u github.com/go-playground/overalls
      - run: overalls -project=github.com/tomatool/tomato -covermode=set -debug -- -v

      - run: mkdir -p /tmp/unit-test
      - run: mv overalls.coverprofile /tmp/unit-test/unit-coverage.out

      - persist_to_workspace:
          root: /tmp/unit-test
          paths:
            - unit-coverage.out

  tomato-test:
    docker:
      - image: docker/compose:1.22.0

    working_directory: /go/src/github.com/tomatool/tomato
    steps:
      - checkout

      - setup_remote_docker

      - run:
          name: run integration test
          command: docker-compose up --abort-on-container-exit --build

      - run: docker-compose start tomato

      - run: mkdir -p /tmp/tomato-test
      - run: docker cp "$(docker-compose ps -q tomato)":/tmp/coverage.out /tmp/tomato-test/tomato-coverage.out
      - persist_to_workspace:
          root: /tmp/tomato-test
          paths:
            - tomato-coverage.out

  codecov-report:
    docker:
      - image: circleci/golang:1.11

    working_directory: /go/src/github.com/tomatool/tomato
    steps:
      - attach_workspace:
          at: /tmp/

      - run: go get -u github.com/wadey/gocovmerge
      - run: gocovmerge /tmp/tomato-coverage.out /tmp/unit-coverage.out > coverage.out
      - run: bash <(curl -s https://codecov.io/bash)


workflows:
  version: 2
  tests:
    jobs:
      - dictionary-check
      - unit-test:
          requires:
              - dictionary-check
      - tomato-test:
          requires:
              - dictionary-check
      - codecov-report:
          requires:
              - unit-test
              - tomato-test
