---

resources:
  - name: http
    type: http
    params:
      base_url: http://localhost:9090
      timeout: 5s
  - name: db1
    type: sqldb
    params:
      driver: postgres
      datasource: postgres://user:pass@localhost:5432/my_awesome_service?sslmode=disable
