---

resources:
    - name: tomato-psql
      type: postgres
      ready_check: true
      params:
        datasource: {{ .PSQL_DATASOURCE }}

    - name: tomato-mysql
      type: mysql
      ready_check: true
      params:
        datasource: {{ .MYSQL_DATASOURCE }}

    - name: tomato-queue
      type: rabbitmq
      ready_check: true
      params:
        datasource: {{ .RABBITMQ_DATASOURCE }}

    - name: tomato-nsq
      type: nsq
      ready_check: true
      params:
        nsqd: {{ .NSQ_DATASOURCE }}

    - name: tomato-wiremock
      type: wiremock
      ready_check: true
      params:
        host: {{ .HTTP_SERVER_HOST }}
        port: {{ .HTTP_SERVER_PORT }}

    - name: tomato-http-client
      type: httpclient
      params:
        base_url: {{ .HTTP_CLIENT_BASE_URL }}

    - name: shell-cli
      type: shell
      ready_check: false