---

resources:
    - name: tomato-psql
      type: db/sql
      params:
        driver: postgres
        datasource: postgres://tomato:potato@localhost:5432/tomato?sslmode=disable
    - name: tomato-mysql
      type: db/sql
      params:
        driver: mysql
        datasource: root:potato@tcp(localhost:3306)/tomato
        
    - name: tomato-queue
      type: queue
      params:
        driver: rabbitmq
        datasource: amqp://guest:guest@localhost:5672
        
    - name: tomato-http-server
      type: http/server
      params:
        port: :8092
    - name: tomato-http-client
      type: http/client
      params:
        base_url: http://localhost:8092
