---

resources:
  - name: http
    type: http/client
    params:
      base_url: http://localhost:8093
      timeout: 5s
  - name: db1
    type: db/sql
    params:
      driver: postgres
      datasource: postgres://user:pass@localhost:5432/my_awesome_service?sslmode=disable
  - name: service-a
    type: http/server
    params:
      port: ":8093"
