---

resources:
    - name: tomato-psql
      type: postgres
      params:
        datasource: {{ .PSQL_DATASOURCE }}

    - name: tomato-mysql
      type: mysql
      params:
        datasource: {{ .MYSQL_DATASOURCE }}

    - name: tomato-queue
      type: rabbitmq
      params:
        datasource: {{ .RABBITMQ_DATASOURCE }}
        stubs_path: "/stubs"

    - name: tomato-nsq
      type: nsq
      params:
        nsqd: {{ .NSQ_DATASOURCE }}
        stubs_path: "/stubs"

    - name: tomato-wiremock
      type: wiremock
      params:
        base_url: {{ .WIREMOCK_BASE_URL }}

    - name: tomato-http-client
      type: httpclient
      params:
        base_url: {{ .HTTP_CLIENT_BASE_URL }}

    - name: shell-cli
      type: shell

    - name: ls
      type: shell
      params:
        prefix: "ls"
