---

resources:
    - name: tomato-psql
      type: database/sql
      params:
        driver: postgres
        datasource: {{ .PSQL_DATASOURCE }}
    - name: tomato-mysql
      type: database/sql
      params:
        driver: mysql
        datasource: {{ .MYSQL_DATASOURCE }}

    - name: tomato-queue
      type: queue
      params:
        driver: rabbitmq
        datasource: {{ .RABBITMQ_DATASOURCE }}

    - name: tomato-http-server
      type: http/server
      params:
        port: {{ .HTTP_SERVER_PORT }}

    - name: tomato-http-client
      type: http/client
      params:
        base_url: {{ .HTTP_CLIENT_BASE_URL }}
