version: '2'
services:

    postgres:
        image: postgres:9.5
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: user
            POSTGRES_PASSWORD: pass
            POSTGRES_DB: my_awesome_service
